packages:
  - 'apps/admin'
  - 'apps/api'
  - 'apps/web'
  - 'apps/e2e'
  - 'packages/database'
  - 'packages/api-contract'
  - '!packages/queue'
  - '!packages/ui'
  - '!packages/sdk'
  - '!packages/core'
  - '!packages/testing'
  - '!packages/api-contract'
