packages:
  # apps
  - 'apps/admin'
  - 'apps/api'
  - 'apps/web'
  - 'apps/e2e'
  # packages
  - 'packages/api-contract'
  - 'packages/config'
  - 'packages/core'
  - 'packages/logger'
  - 'packages/sdk'
  - 'packages/database'

  - 'packages/ui'

  - 'packages/testing'
