# postgres:17 이미지 기반
# Description : Dockerfile.db - 📌 db docker build
# Author : Shiwoo Min
# Date : 2025-09-18

# 1. Postgres 이미지
FROM cgr.dev/chainguard/postgres:latest AS db

# 타임존 설정
ENV TZ=Asia/Seoul

# 2. 설정 파일 복사
COPY infra/database/conf/postgresql.conf /etc/postgresql/postgresql.conf
COPY infra/database/conf/pg_hba.conf     /etc/postgresql/pg_hba.conf

# 3. 초기화 스크립트 복사
COPY infra/database/init/ /docker-entrypoint-initdb.d/
