-- Description : 20-ddl.sql - 📌 PostgreSQL Table DDL with Comments
-- Author : Shiwoo Min
-- Date : 2025-09-07
-- 09-24 : SSO + 로컬 통합형으로 테이블 수정

-- USERS
CREATE TABLE users (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email           CITEXT UNIQUE,
  name            TEXT,
  last_login_at   TIMESTAMPTZ,
  role_flags      INT DEFAULT 0,
  preferences     JSONB DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- AUTH_PROVIDERS (모든 인증 수단 통합: local, google, kakao, github 등)
CREATE TABLE auth_providers (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider       TEXT NOT NULL,   -- 'local', 'google', 'kakao', 'github' ...
  provider_sub   TEXT,            -- 외부 식별자 (google_sub 등)
  password_hash  TEXT,            -- 로컬 인증 전용 (bcrypt/argon2 해시)
  meta           JSONB DEFAULT '{}'::jsonb,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_provider_sub UNIQUE (provider, provider_sub) WHERE provider_sub IS NOT NULL,
  CONSTRAINT uq_user_local UNIQUE (user_id) WHERE provider = 'local'
);

-- SESSIONS
CREATE TABLE sessions (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id           BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  starts_at            TIMESTAMPTZ NOT NULL,
  ends_at              TIMESTAMPTZ NOT NULL,
  capacity             INT,
  participant_fee      INT,
  status               TEXT NOT NULL DEFAULT 'SCHEDULED',
  room_reservation_id  BIGINT UNIQUE,
  location_text        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT sessions_time_order CHECK (ends_at > starts_at),
  CONSTRAINT sessions_status_ck CHECK (status IN ('SCHEDULED','CONFIRMED','CANCELLED','COMPLETED'))
);

-- VENUES
CREATE TABLE venues (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL,
  address         TEXT,
  opening_hours   JSONB,
  blackout_rules  JSONB,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ROOMS
CREATE TABLE rooms (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id        BIGINT NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  capacity        INT,
  status          TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT rooms_uniq_per_venue UNIQUE (venue_id, name),
  CONSTRAINT rooms_status_ck CHECK (status IN ('ACTIVE','INACTIVE','MAINTENANCE'))
);

-- ROOM_RESERVATIONS
CREATE TABLE room_reservations (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id      BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  user_id      BIGINT REFERENCES users(id) ON DELETE SET NULL,
  starts_at    TIMESTAMPTZ NOT NULL,
  ends_at      TIMESTAMPTZ NOT NULL,
  period       TSTZRANGE GENERATED ALWAYS AS (tstzrange(starts_at, ends_at, '[)')) STORED,
  purpose      TEXT,
  status       TEXT NOT NULL DEFAULT 'PENDING',
  meta         JSONB DEFAULT '{}'::jsonb,
  session_id   BIGINT UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT rr_time_order CHECK (ends_at > starts_at),
  CONSTRAINT rr_status_ck CHECK (status IN ('PENDING','CONFIRMED','CANCELLED','COMPLETED'))
);

-- 예약과 세션의 상호 참조 (1:1 연결, DEFERRABLE 허용)
ALTER TABLE sessions
  ADD CONSTRAINT sessions_room_reservation_fk
  FOREIGN KEY (room_reservation_id) REFERENCES room_reservations(id)
  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE room_reservations
  ADD CONSTRAINT rr_session_fk
  FOREIGN KEY (session_id) REFERENCES sessions(id)
  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- 겹치는 예약 방지 (같은 방, 상태 PENDING/CONFIRMED만 제한)
ALTER TABLE room_reservations
  ADD CONSTRAINT room_reservations_no_overlap
  EXCLUDE USING gist (
    room_id WITH =,
    period  WITH &&
  )
  WHERE (status IN ('PENDING','CONFIRMED'));

-- PROGRAM_PARTICIPANTS
CREATE TABLE program_participants (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id   BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role         TEXT NOT NULL DEFAULT 'ATTENDEE',
  status       TEXT NOT NULL DEFAULT 'APPLIED',
  joined_at    TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT program_participants_uniq UNIQUE (session_id, user_id),
  CONSTRAINT pp_role_ck   CHECK (role IN ('HOST','ATTENDEE')),
  CONSTRAINT pp_status_ck CHECK (status IN ('APPLIED','CONFIRMED','CANCELLED','NO_SHOW'))
);

-- AI_INTERACTIONS
CREATE TABLE ai_interactions (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            BIGINT REFERENCES users(id) ON DELETE SET NULL,
  program_id         BIGINT REFERENCES programs(id) ON DELETE SET NULL,
  session_id         BIGINT REFERENCES sessions(id) ON DELETE SET NULL,
  provider           TEXT NOT NULL,
  model              TEXT NOT NULL,
  kind               TEXT NOT NULL,
  prompt_tokens      INT  DEFAULT 0,
  completion_tokens  INT  DEFAULT 0,
  cost               NUMERIC(12,6) DEFAULT 0,
  status             TEXT NOT NULL DEFAULT 'OK',
  trace_id           TEXT,
  meta               JSONB DEFAULT '{}'::jsonb,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ai_status_ck CHECK (status IN ('OK','ERROR'))
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_programs_created_by_user_id   ON programs(created_by_user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_program_id           ON sessions(program_id);
CREATE INDEX IF NOT EXISTS idx_sessions_starts_at            ON sessions(starts_at);
CREATE INDEX IF NOT EXISTS idx_room_reservations_room_id     ON room_reservations(room_id);
CREATE INDEX IF NOT EXISTS idx_room_reservations_starts_at   ON room_reservations(starts_at);
CREATE INDEX IF NOT EXISTS idx_room_reservations_status      ON room_reservations(status);
CREATE INDEX IF NOT EXISTS idx_program_participants_user     ON program_participants(user_id);
CREATE INDEX IF NOT EXISTS idx_program_participants_session  ON program_participants(session_id);
CREATE INDEX IF NOT EXISTS idx_ai_interactions_user          ON ai_interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_interactions_program       ON ai_interactions(program_id);
CREATE INDEX IF NOT EXISTS idx_ai_interactions_session       ON ai_interactions(session_id);
CREATE INDEX IF NOT EXISTS idx_ai_interactions_created_at    ON ai_interactions(created_at);

-- TRIGGERS (updated_at 자동 갱신)
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END$$;

CREATE TRIGGER trg_users_u BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_programs_u BEFORE UPDATE ON programs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sessions_u BEFORE UPDATE ON sessions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_venues_u BEFORE UPDATE ON venues
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_rooms_u BEFORE UPDATE ON rooms
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_rr_u BEFORE UPDATE ON room_reservations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 완료 로그
DO $$
BEGIN
    RAISE NOTICE 'Database schema (DDL) created successfully';
END$$;
