-- Description : 20-ddl.sql - 📌 PostgreSQL Table DDL with Comments
-- Author      : Shiwoo Min
-- Date        : 2025-09-07
--
-- NOTE:
--   - Requires extensions installed beforehand (from 00-extensions.sql):
--       citext, btree_gist
--   - Server timezone/log_timezone configured in postgresql.conf (e.g., 'Asia/Seoul').

------------------------------------------------------------
-- ================ USERS =================
------------------------------------------------------------
CREATE TABLE users (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 사용자 고유 ID
  email           CITEXT UNIQUE,               -- 구글 이메일 (고유, NULL 허용 시 여러 NULL 가능)
  name            TEXT,                        -- 이름
  google_sub      TEXT UNIQUE,                 -- Google OIDC sub
  last_login_at   TIMESTAMPTZ,                 -- 최근 로그인 시간
  role_flags      INT DEFAULT 0,               -- 권한 플래그 (비트 연산용)
  preferences     JSONB DEFAULT '{}'::jsonb,   -- 사용자 설정 정보
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(), -- 생성 시각
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()  -- 수정 시각
);

------------------------------------------------------------
-- ================ PROGRAMS =================
------------------------------------------------------------
CREATE TABLE programs (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 프로그램 ID
  created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT, -- 생성자 (User FK)
  type               TEXT,                         -- 프로그램 유형 (세미나 등)
  title              TEXT NOT NULL,                -- 제목
  description        TEXT,                         -- 설명
  ai_summary_tags    JSONB DEFAULT '[]'::jsonb,    -- AI 요약 태그
  is_active          BOOLEAN NOT NULL DEFAULT true,-- 활성 여부
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

------------------------------------------------------------
-- ================ SESSIONS =================
------------------------------------------------------------
CREATE TABLE sessions (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 세션 ID
  program_id           BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE, -- 프로그램 ID
  starts_at            TIMESTAMPTZ NOT NULL,          -- 시작 시간
  ends_at              TIMESTAMPTZ NOT NULL,          -- 종료 시간
  capacity             INT,                           -- 수용 인원
  participant_fee      INT,                           -- 참가비
  status               TEXT NOT NULL DEFAULT 'SCHEDULED', -- 상태
  room_reservation_id  BIGINT UNIQUE,                 -- 예약 ID (옵션, 1:1 연결용)
  location_text        TEXT,                          -- 장소 설명
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT sessions_time_order CHECK (ends_at > starts_at),
  CONSTRAINT sessions_status_ck CHECK (status IN ('SCHEDULED','CONFIRMED','CANCELLED','COMPLETED'))
);

------------------------------------------------------------
-- ================ VENUES =================
------------------------------------------------------------
CREATE TABLE venues (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 지점 ID
  name            TEXT NOT NULL,               -- 지점명
  address         TEXT,                        -- 주소
  opening_hours   JSONB,                       -- 운영시간
  blackout_rules  JSONB,                       -- 예약 제한 규칙
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

------------------------------------------------------------
-- ================ ROOMS =================
------------------------------------------------------------
CREATE TABLE rooms (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 방 ID
  venue_id        BIGINT NOT NULL REFERENCES venues(id) ON DELETE CASCADE, -- 지점 ID
  name            TEXT NOT NULL,               -- 방 이름
  capacity        INT,                         -- 정원
  status          TEXT NOT NULL DEFAULT 'ACTIVE', -- 방 상태
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT rooms_uniq_per_venue UNIQUE (venue_id, name),
  CONSTRAINT rooms_status_ck CHECK (status IN ('ACTIVE','INACTIVE','MAINTENANCE'))
);

------------------------------------------------------------
-- ================ ROOM_RESERVATIONS =================
------------------------------------------------------------
CREATE TABLE room_reservations (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 예약 ID
  room_id      BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE, -- 방 ID
  user_id      BIGINT REFERENCES users(id) ON DELETE SET NULL,      -- 사용자 ID (NULL 허용으로 보존)
  starts_at    TIMESTAMPTZ NOT NULL,           -- 시작 시간
  ends_at      TIMESTAMPTZ NOT NULL,           -- 종료 시간
  period       TSTZRANGE GENERATED ALWAYS AS (tstzrange(starts_at, ends_at, '[)')) STORED, -- 시간 범위
  purpose      TEXT,                            -- 용도
  status       TEXT NOT NULL DEFAULT 'PENDING', -- 예약 상태
  meta         JSONB DEFAULT '{}'::jsonb,       -- 메타 정보
  session_id   BIGINT UNIQUE,                   -- 연계 세션 ID(1:1 연결용)
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT rr_time_order CHECK (ends_at > starts_at),
  CONSTRAINT rr_status_ck CHECK (status IN ('PENDING','CONFIRMED','CANCELLED','COMPLETED'))
);

-- 예약과 세션의 상호 참조(1:1 연결) - DEFERRABLE로 상호 의존 삽입 허용
ALTER TABLE sessions
  ADD CONSTRAINT sessions_room_reservation_fk
  FOREIGN KEY (room_reservation_id) REFERENCES room_reservations(id)
  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE room_reservations
  ADD CONSTRAINT rr_session_fk
  FOREIGN KEY (session_id) REFERENCES sessions(id)
  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- 겹치는 예약 방지: 같은 방에서 PENDING/CONFIRMED 상태끼리 시간 겹침 금지
-- NOTE: requires btree_gist (for room_id WITH =)
ALTER TABLE room_reservations
  ADD CONSTRAINT room_reservations_no_overlap
  EXCLUDE USING gist (
    room_id WITH =,
    period  WITH &&
  )
  WHERE (status IN ('PENDING','CONFIRMED'));

------------------------------------------------------------
-- ================ PROGRAM_PARTICIPANTS =================
------------------------------------------------------------
CREATE TABLE program_participants (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 참여 ID
  session_id   BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, -- 세션 ID
  user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,    -- 사용자 ID
  role         TEXT NOT NULL DEFAULT 'ATTENDEE', -- 역할
  status       TEXT NOT NULL DEFAULT 'APPLIED',  -- 상태
  joined_at    TIMESTAMPTZ DEFAULT now(),        -- 참여 시각
  CONSTRAINT program_participants_uniq UNIQUE (session_id, user_id),
  CONSTRAINT pp_role_ck   CHECK (role IN ('HOST','ATTENDEE')),
  CONSTRAINT pp_status_ck CHECK (status IN ('APPLIED','CONFIRMED','CANCELLED','NO_SHOW'))
);

------------------------------------------------------------
-- ================ AI_INTERACTIONS =================
------------------------------------------------------------
CREATE TABLE ai_interactions (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- AI 요청 ID
  user_id            BIGINT REFERENCES users(id) ON DELETE SET NULL,      -- 사용자 (NULL 허용으로 보존)
  program_id         BIGINT REFERENCES programs(id) ON DELETE SET NULL,   -- 프로그램 (옵션)
  session_id         BIGINT REFERENCES sessions(id) ON DELETE SET NULL,   -- 세션 (옵션)
  provider           TEXT NOT NULL,               -- OpenAI 등
  model              TEXT NOT NULL,               -- GPT-4 등
  kind               TEXT NOT NULL,               -- chat/embed 등
  prompt_tokens      INT  DEFAULT 0,              -- 요청 토큰
  completion_tokens  INT  DEFAULT 0,              -- 응답 토큰
  cost               NUMERIC(12,6) DEFAULT 0,     -- 비용
  status             TEXT NOT NULL DEFAULT 'OK',  -- 상태
  trace_id           TEXT,                        -- 추적 ID
  meta               JSONB DEFAULT '{}'::jsonb,   -- 부가정보
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ai_status_ck CHECK (status IN ('OK','ERROR'))
);

------------------------------------------------------------
-- ================ INDEXES =================
------------------------------------------------------------
-- FK 및 조회 패턴 보강 인덱스
CREATE INDEX IF NOT EXISTS idx_programs_created_by_user_id   ON programs(created_by_user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_program_id           ON sessions(program_id);
CREATE INDEX IF NOT EXISTS idx_sessions_starts_at            ON sessions(starts_at);
CREATE INDEX IF NOT EXISTS idx_room_reservations_room_id     ON room_reservations(room_id);
CREATE INDEX IF NOT EXISTS idx_room_reservations_starts_at   ON room_reservations(starts_at);
CREATE INDEX IF NOT EXISTS idx_room_reservations_status      ON room_reservations(status);
CREATE INDEX IF NOT EXISTS idx_program_participants_user     ON program_participants(user_id);
CREATE INDEX IF NOT EXISTS idx_program_participants_session  ON program_participants(session_id);
CREATE INDEX IF NOT EXISTS idx_ai_interactions_user          ON ai_interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_interactions_program       ON ai_interactions(program_id);
CREATE INDEX IF NOT EXISTS idx_ai_interactions_session       ON ai_interactions(session_id);
CREATE INDEX IF NOT EXISTS idx_ai_interactions_created_at    ON ai_interactions(created_at);

------------------------------------------------------------
-- ================ TRIGGERS (UPDATED_AT) =================
------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END$$;

-- updated_at 컬럼이 있는 테이블에만 연결
CREATE TRIGGER trg_users_u BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_programs_u BEFORE UPDATE ON programs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_sessions_u BEFORE UPDATE ON sessions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_venues_u BEFORE UPDATE ON venues
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_rooms_u BEFORE UPDATE ON rooms
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_rr_u BEFORE UPDATE ON room_reservations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Log DDL completion
DO $$
BEGIN
    RAISE NOTICE 'Database schema (DDL) created successfully';
END$$;
