-- Description : 20-ddl.sql - 📌 PostgreSQL Table DDL with Comments (Revised)
-- Author : Shiwoo Min
-- Date : 2025-09-27
-- Schema : ConnectWon MVP (Users, Auth, Programs, Venues, Devices, Reviews, Logs)

-- Ensure required extensions
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- USERS
CREATE TABLE users (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email           CITEXT UNIQUE,
  name            TEXT,
  last_login_at   TIMESTAMPTZ,
  role_flags      INT DEFAULT 0,
  preferences     JSONB DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- AUTH_PROVIDERS
CREATE TABLE auth_providers (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider       TEXT NOT NULL,
  provider_sub   TEXT,
  password_hash  TEXT,
  meta           JSONB DEFAULT '{}'::jsonb,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Partial Unique Indexes
CREATE UNIQUE INDEX uq_provider_sub
  ON auth_providers(provider, provider_sub)
  WHERE provider_sub IS NOT NULL;

CREATE UNIQUE INDEX uq_user_local
  ON auth_providers(user_id)
  WHERE provider = 'local';

-- PROGRAMS
CREATE TABLE programs (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title             TEXT NOT NULL,
  description       TEXT,
  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  category          TEXT,
  meta              JSONB DEFAULT '{}'::jsonb,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- SESSIONS
CREATE TABLE sessions (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id           BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  starts_at            TIMESTAMPTZ NOT NULL,
  ends_at              TIMESTAMPTZ NOT NULL,
  capacity             INT,
  participant_fee      INT,
  status               TEXT NOT NULL DEFAULT 'SCHEDULED',
  room_reservation_id  BIGINT UNIQUE,
  location_text        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT sessions_time_order CHECK (ends_at > starts_at),
  CONSTRAINT sessions_status_ck CHECK (status IN ('SCHEDULED','CONFIRMED','CANCELLED','COMPLETED'))
);

-- VENUES
CREATE TABLE venues (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL,
  address         TEXT,
  opening_hours   JSONB,
  blackout_rules  JSONB,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ROOMS
CREATE TABLE rooms (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id        BIGINT NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  capacity        INT,
  status          TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT rooms_uniq_per_venue UNIQUE (venue_id, name),
  CONSTRAINT rooms_status_ck CHECK (status IN ('ACTIVE','INACTIVE','MAINTENANCE'))
);

-- ROOM_RESERVATIONS
CREATE TABLE room_reservations (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id      BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  user_id      BIGINT REFERENCES users(id) ON DELETE SET NULL,
  starts_at    TIMESTAMPTZ NOT NULL,
  ends_at      TIMESTAMPTZ NOT NULL,
  period       TSTZRANGE GENERATED ALWAYS AS (tstzrange(starts_at, ends_at, '[)')) STORED,
  purpose      TEXT,
  status       TEXT NOT NULL DEFAULT 'PENDING',
  meta         JSONB DEFAULT '{}'::jsonb,
  session_id   BIGINT UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT rr_time_order CHECK (ends_at > starts_at),
  CONSTRAINT rr_status_ck CHECK (status IN ('PENDING','CONFIRMED','CANCELLED','COMPLETED'))
);

-- SESSIONS <-> ROOM_RESERVATIONS (1:1)
ALTER TABLE sessions
  ADD CONSTRAINT sessions_room_reservation_fk
  FOREIGN KEY (room_reservation_id) REFERENCES room_reservations(id)
  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE room_reservations
  ADD CONSTRAINT rr_session_fk
  FOREIGN KEY (session_id) REFERENCES sessions(id)
  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- 겹치는 예약 방지
ALTER TABLE room_reservations
  ADD CONSTRAINT room_reservations_no_overlap
  EXCLUDE USING gist (
    room_id WITH =,
    period  WITH &&
  )
  WHERE (status IN ('PENDING','CONFIRMED'));

-- PROGRAM_PARTICIPANTS
CREATE TABLE program_participants (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id   BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role         TEXT NOT NULL DEFAULT 'ATTENDEE',
  status       TEXT NOT NULL DEFAULT 'APPLIED',
  joined_at    TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT program_participants_uniq UNIQUE (session_id, user_id),
  CONSTRAINT pp_role_ck   CHECK (role IN ('HOST','ATTENDEE')),
  CONSTRAINT pp_status_ck CHECK (status IN ('APPLIED','CONFIRMED','CANCELLED','NO_SHOW'))
);

-- DEVICES
CREATE TABLE devices (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  type        TEXT,
  specs       JSONB DEFAULT '{}'::jsonb,
  status      TEXT NOT NULL DEFAULT 'AVAILABLE',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT devices_status_ck CHECK (status IN ('AVAILABLE','IN_USE','MAINTENANCE','RETIRED'))
);

-- DEVICE_RENTALS
CREATE TABLE device_rentals (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id   BIGINT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  starts_at   TIMESTAMPTZ NOT NULL,
  ends_at     TIMESTAMPTZ NOT NULL,
  status      TEXT NOT NULL DEFAULT 'PENDING',
  meta        JSONB DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT device_rentals_status_ck CHECK (status IN ('PENDING','APPROVED','RETURNED','CANCELLED'))
);

-- 겹치는 대여 방지
ALTER TABLE device_rentals
  ADD CONSTRAINT device_rentals_no_overlap
  EXCLUDE USING gist (
    device_id WITH =,
    tstzrange(starts_at, ends_at, '[)') WITH &&
  )
  WHERE (status IN ('PENDING','APPROVED'));

-- AI_INTERACTIONS
CREATE TABLE ai_interactions (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            BIGINT REFERENCES users(id) ON DELETE SET NULL,
  program_id         BIGINT REFERENCES programs(id) ON DELETE SET NULL,
  session_id         BIGINT REFERENCES sessions(id) ON DELETE SET NULL,
  provider           TEXT NOT NULL,
  model              TEXT NOT NULL,
  kind               TEXT NOT NULL,
  prompt_tokens      INT  DEFAULT 0,
  completion_tokens  INT  DEFAULT 0,
  cost               NUMERIC(12,6) DEFAULT 0,
  status             TEXT NOT NULL DEFAULT 'OK',
  trace_id           TEXT,
  meta               JSONB DEFAULT '{}'::jsonb,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ai_status_ck CHECK (status IN ('OK','ERROR'))
);

-- USER_ACTIVITIES
CREATE TABLE user_activities (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action      TEXT NOT NULL,
  entity_type TEXT,
  entity_id   BIGINT,
  meta        JSONB DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- REVIEWS
CREATE TABLE reviews (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_type TEXT NOT NULL,         -- 'program','session','room','device'
  target_id   BIGINT NOT NULL,
  rating      INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment     TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- NOTIFICATIONS
CREATE TABLE notifications (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type        TEXT NOT NULL,        -- 'reservation','device','program','system'
  title       TEXT NOT NULL,
  message     TEXT,
  is_read     BOOLEAN DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- TRIGGERS (updated_at 자동 갱신)
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END$$;

CREATE TRIGGER trg_users_u BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_programs_u BEFORE UPDATE ON programs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sessions_u BEFORE UPDATE ON sessions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_venues_u BEFORE UPDATE ON venues FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_rooms_u BEFORE UPDATE ON rooms FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_rr_u BEFORE UPDATE ON room_reservations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_devices_u BEFORE UPDATE ON devices FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_device_rentals_u BEFORE UPDATE ON device_rentals FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_reviews_u BEFORE UPDATE ON reviews FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 완료 로그
DO $$
BEGIN
    RAISE NOTICE 'Database schema (DDL) created successfully (14 tables)';
END$$;
